// Open the browser's print dialog (used for "Export PDF" → Save as PDF).
//
// We render the content into a hidden <iframe> and print that, instead of
// window.open(). Pop-up windows are unreliable: browsers block them, and
// window.open(..., "noopener") returns null so there's no handle to write to.
// An iframe always works and needs no pop-up permission.
export function openPrintWindow({ title, contentText }) {
  const safeTitle = String(title || "Study Buddy");
  const safeText = String(contentText || "");

  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(safeTitle)}</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; padding: 24px; color: #111; }
      h1 { font-size: 18px; margin: 0 0 12px; }
      pre { white-space: pre-wrap; word-break: break-word; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace; font-size: 12px; line-height: 1.5; }
      .meta { color: #555; font-size: 12px; margin-bottom: 16px; }
      @media print { body { padding: 0; } }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(safeTitle)}</h1>
    <div class="meta">Generated by Study Buddy</div>
    <pre>${escapeHtml(safeText)}</pre>
  </body>
</html>`;

  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  document.body.appendChild(iframe);

  const remove = () => {
    if (iframe.parentNode) iframe.parentNode.removeChild(iframe);
  };

  const doc = iframe.contentWindow && iframe.contentWindow.document;
  if (!doc) {
    remove();
    return false;
  }

  doc.open();
  doc.write(html);
  doc.close();

  let done = false;
  const run = () => {
    if (done) return;
    done = true;
    try {
      const win = iframe.contentWindow;
      win.focus();
      // Clean up once the print dialog closes (where supported).
      win.onafterprint = remove;
      win.print();
    } catch {
      remove();
    }
  };

  // Give the iframe a tick to lay out its content before printing.
  if (iframe.contentWindow.document.readyState === "complete") {
    setTimeout(run, 250);
  } else {
    iframe.onload = () => setTimeout(run, 100);
    setTimeout(run, 700); // fallback if onload doesn't fire
  }

  // Safety net: remove the iframe even if onafterprint never fires.
  setTimeout(remove, 60000);
  return true;
}

function escapeHtml(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}
