export function openPrintWindow({ title, contentText }) {
  const w = window.open("", "_blank", "noopener,noreferrer");
  if (!w) return false;

  const safeTitle = String(title || "Study Buddy");
  const safeText = String(contentText || "");

  w.document.open();
  w.document.write(`<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${safeTitle}</title>
    <style>
      body { font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Arial; padding: 24px; color: #111; }
      h1 { font-size: 18px; margin: 0 0 12px; }
      pre { white-space: pre-wrap; word-break: break-word; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, Liberation Mono, Courier New, monospace; font-size: 12px; line-height: 1.5; }
      .meta { color: #555; font-size: 12px; margin-bottom: 16px; }
      @media print { body { padding: 0; } }
    </style>
  </head>
  <body>
    <h1>${safeTitle}</h1>
    <div class="meta">Generated by Study Buddy</div>
    <pre>${escapeHtml(safeText)}</pre>
    <script>
      setTimeout(() => { window.focus(); window.print(); }, 150);
    </script>
  </body>
</html>`);
  w.document.close();
  return true;
}

function escapeHtml(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

